DESTDIR=debian/led-matrix-control

install:
	install -D script/led-matrix-control $(DESTDIR)/usr/bin/led-matrix-control
	install -D service/led-matrix-control.service $(DESTDIR)/etc/systemd/system/led-matrix-control.service
